Update linter.yml

diff --git a/.github/workflows/linter.yml b/.github/workflows/linter.yml
--- a/.github/workflows/linter.yml
+++ b/.github/workflows/linter.yml
@@ -1,19 +1,21 @@
-name: Super Linter
+name: cpp-linter
 
-on:
-  push
+on: push
 
 jobs:
-  lint:
+  cpp-linter:
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout repository
-      uses: github/super-linter@v4.10.0
-    - name: Install super-linter
-      run: |
-        git clone https://github.com/github/super-linter.git
-        cd super-linter
-        ./install.sh
-    - name: Run super-linter
-      run: |
-        super-linter
+      - uses: actions/checkout@v3
+      - uses: cpp-linter/cpp-linter-action@v2
+        id: linter
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          style: file
+
+      - name: Fail fast?!
+        if: steps.linter.outputs.checks-failed > 0
+        run: echo "Some files failed the linting checks!"
+        # for actual deployment
+        # run: exit 1
